/**
 * "✨ Improve with Claude" — clipboard-mode helper.
 *
 * Builds a richer-than-default prompt that includes:
 *   1. Project meta (name, description, RN flavor) from package.json
 *   2. Per-screen "peeks" — JSDoc, imports, top string literals — extracted
 *      directly from each route's component file
 *   3. The current snap-flows.ts contents for diff/refinement
 *
 * The user pastes this into Claude Code, gets back a regrouped snap-flows.ts,
 * saves over the original. Capture stays out of API billing — clipboard is
 * the integration surface.
 *
 * Same RPC powers both the post-install wizard step (auto-suggested after
 * scan) and the dashboard "✨ Improve" button (manual refinement later).
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import { findProjectForBridge } from "./init";

export interface ImproveResult {
	/** Single string the view copies to the clipboard. */
	clipboardPayload: string;
	/** The path to snap-flows.ts so the toast can reference it. */
	flowsFilePath: string;
	/** Human summary for the toast (e.g. "47 screens, 14 flows"). */
	summary: string;
}

const SCREEN_EXT = /\.(tsx|ts|jsx|js)$/;
const SKIP_FILE = /\.(test|spec|stories|d)\./;
// Strings under 3 chars or all-symbol/all-numeric are noise — don't
// surface them as "screen content hints" to the LLM.
const STRING_NOISE = /^[\s\d\W]+$/;

interface ScreenPeek {
	route: string;
	filePath: string;
	imports: string[];
	docComment?: string;
	topStrings: string[];
}

interface ProjectMeta {
	name: string;
	description?: string;
	rnVersion?: string;
	expoVersion?: string;
}

const PROMPT_HEADER = `# Improve snap-flows.ts

You're going to regroup an Expo Router app's screens into user-journey-shaped
flows. The current snap-flows.ts (at the bottom) was generated by a path-based
heuristic — it groups by URL prefix, which doesn't reflect how a real user
moves through the product.

## Rules

1. Keep every \`route\` value VERBATIM — no edits to paths.
2. Group by user journey, not by URL prefix. Examples:
   - \`/sign-in\`, \`/sign-up\`, \`/forgot-password\` → an "Auth" flow even if
     they live under different URL prefixes.
   - Booking-related screens (browse, pick activity, payment, confirmation) →
     a "Booking" flow with sub-flows for sub-steps.
   - Profile + settings + account management → "Profile / settings".
3. Use sub-flows (\`flows: [...]\`) for genuinely nested experiences. Don't
   over-nest — keep depth ≤ 2.
4. Display order should mirror a natural product walkthrough — onboarding
   first, primary feature loops next, settings/admin last.
5. Screen \`name\` should match feature-uppercase product wording, not
   route slugs ("Booking summary" not "Booking-summary"). Prefer names that
   align with what the JSDoc / top string literals suggest.
6. Add \`stateHash\` filters where two routes share a path but differ in
   meaningful state (e.g. logged-out vs logged-in home, modal-open vs base).
7. Preserve the \`SnapFlowsDeclaration\` type contract. Output the FULL
   updated file, ready to paste over the existing one.

## How to read the context below

- **Project context**: name + description from package.json. Tells you the
  product domain.
- **Screen peeks**: for each route, an auto-extracted slice of its component
  file — JSDoc above the default export, imports (a hint about which UI
  primitives + state stores are used), and string literals near the JSX top
  (often screen titles, button labels, headings). Use these to infer screen
  *purpose*, not just route name.
- **Current snap-flows.ts**: the heuristic baseline you're improving.

`;

const PROMPT_FOOTER = `

## Output

Return the entire updated snap-flows.ts contents in a single \`\`\`ts code
fence. After the file, give me a 2-3 line summary of what you changed
(added flows, renamed screens, sub-flow restructuring) so I can scan it
quickly before saving.
`;

/**
 * Walk app/ and produce screen peeks. Mirrors snap-flows-scan's walk so
 * route → file mapping stays consistent.
 */
function gatherScreenPeeks(rnAppDir: string): ScreenPeek[] {
	const appDir = join(rnAppDir, "app");
	if (!existsSync(appDir)) return [];
	const found: { route: string; full: string; rel: string }[] = [];
	walkApp(appDir, "", appDir, found);
	found.sort((a, b) => a.route.localeCompare(b.route));
	return found.map(({ route, full, rel }) => ({
		route,
		filePath: rel,
		...peekFile(full),
	}));
}

function walkApp(
	dir: string,
	baseRel: string,
	root: string,
	out: { route: string; full: string; rel: string }[],
): void {
	for (const entry of readdirSync(dir)) {
		if (entry.startsWith(".") || entry.startsWith("_")) continue;
		const full = join(dir, entry);
		const stat = statSync(full);
		if (stat.isDirectory()) {
			walkApp(full, `${baseRel}/${entry}`, root, out);
			continue;
		}
		if (!SCREEN_EXT.test(entry)) continue;
		if (SKIP_FILE.test(entry)) continue;
		const route = fileToRoute(`${baseRel}/${entry}`);
		const rel = relative(root, full);
		if (!out.some((r) => r.route === route)) {
			out.push({ route, full, rel });
		}
	}
}

function fileToRoute(relPath: string): string {
	let r = relPath
		.replace(SCREEN_EXT, "")
		.replace(/\.(ios|android|native|web)$/, "")
		.replace(/\/index$/, "");
	const segs = r
		.split("/")
		.filter((s) => s && !(s.startsWith("(") && s.endsWith(")")));
	let route = `/${segs.join("/")}`;
	route = route.replace(/\[(\.{3})?(\w+)\]/g, ":$2");
	if (route === "") route = "/";
	if (!route.startsWith("/")) route = `/${route}`;
	return route === "//" ? "/" : route;
}

/**
 * Extract a useful slice from a screen file. Reads ~60 lines, pulls:
 *   - imports (signal about UI kit, hooks, state stores)
 *   - JSDoc directly above the default export (often the best summary)
 *   - JSX-adjacent string literals (screen titles, headings, button labels)
 */
function peekFile(absPath: string): {
	imports: string[];
	docComment?: string;
	topStrings: string[];
} {
	let raw: string;
	try {
		raw = readFileSync(absPath, "utf8");
	} catch {
		return { imports: [], topStrings: [] };
	}
	const lines = raw.split("\n").slice(0, 80);
	const imports: string[] = [];
	const topStrings: string[] = [];

	// Find a JSDoc directly above `export default function|const`
	const exportIdx = lines.findIndex((l) =>
		/^\s*export\s+default\s+(function|const|memo|forwardRef|class|\()/.test(l),
	);
	let docComment: string | undefined;
	if (exportIdx > 0) {
		// Walk back looking for a /** ... */ block
		const before = lines.slice(0, exportIdx).join("\n");
		const docMatch = /\/\*\*([\s\S]+?)\*\/(?:[^/]*?)$/.exec(before);
		if (docMatch?.[1]) {
			docComment = docMatch[1]
				.split("\n")
				.map((l) => l.replace(/^\s*\*\s?/, "").trim())
				.filter(Boolean)
				.join(" ")
				.slice(0, 280);
		}
	}

	for (const line of lines) {
		const trimmed = line.trim();
		if (trimmed.startsWith("import ")) {
			imports.push(trimmed);
			continue;
		}
		// String literal harvesting — pull anything that looks like
		// human-facing copy (not paths, not props, not symbols).
		for (const m of line.matchAll(/["'`]([^"'`\n]{3,80})["'`]/g)) {
			const s = m[1];
			if (!s) continue;
			if (s.includes("/") || s.startsWith("@") || s.startsWith("#")) continue;
			if (STRING_NOISE.test(s)) continue;
			if (!/[a-zA-Z]{3,}/.test(s)) continue;
			if (!topStrings.includes(s)) topStrings.push(s);
		}
	}

	return {
		imports: imports.slice(0, 10),
		docComment,
		topStrings: topStrings.slice(0, 6),
	};
}

function readProjectMeta(rnAppDir: string): ProjectMeta {
	const pkgPath = join(rnAppDir, "package.json");
	if (!existsSync(pkgPath)) return { name: "(unknown)" };
	try {
		const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as Record<
			string,
			unknown
		>;
		const deps = (pkg.dependencies ?? {}) as Record<string, string>;
		return {
			name: (pkg.name as string) || "(unknown)",
			description: pkg.description as string | undefined,
			rnVersion: deps["react-native"],
			expoVersion: deps.expo,
		};
	} catch {
		return { name: "(unknown)" };
	}
}

function renderProjectMeta(meta: ProjectMeta): string {
	const lines = [`- Package name: \`${meta.name}\``];
	if (meta.description) lines.push(`- Description: ${meta.description}`);
	if (meta.expoVersion) lines.push(`- Expo: ${meta.expoVersion}`);
	if (meta.rnVersion) lines.push(`- React Native: ${meta.rnVersion}`);
	return lines.join("\n");
}

function renderScreenPeek(p: ScreenPeek): string {
	const sections: string[] = [];
	sections.push(`### \`${p.route}\` → \`${p.filePath}\``);
	if (p.docComment) {
		sections.push(`**JSDoc:** ${p.docComment}`);
	}
	if (p.imports.length > 0) {
		const importBlock = p.imports.map((i) => `  ${i}`).join("\n");
		sections.push(`**Imports:**\n${importBlock}`);
	}
	if (p.topStrings.length > 0) {
		sections.push(
			`**Strings spotted:** ${p.topStrings.map((s) => `"${s}"`).join(", ")}`,
		);
	}
	return sections.join("\n");
}

export function buildImprovePrompt(slug: string): ImproveResult {
	const project = findProjectForBridge(slug);
	if (!project) {
		throw new Error(`No project with slug "${slug}"`);
	}
	const rnAppDir = project.rnAppDir;
	if (!rnAppDir) {
		throw new Error(`Project "${slug}" has no rnAppDir on disk`);
	}

	const flowsFilePath = `${rnAppDir}/snap-flows.ts`;
	let flowsContents: string;
	try {
		flowsContents = readFileSync(flowsFilePath, "utf8");
	} catch (err) {
		throw new Error(
			`Couldn't read ${flowsFilePath}: ${(err as Error).message}. Run snap-flows-scan first.`,
		);
	}

	const meta = readProjectMeta(rnAppDir);
	const peeks = gatherScreenPeeks(rnAppDir);

	// Cross-check what's in app/ against what's already declared in snap-
	// flows.ts. Routes that exist on disk but aren't in the declaration
	// (e.g. designer added a screen yesterday, hasn't run --merge yet) are
	// surfaced to Claude with a "place these in the right user-journey
	// flow" hint, so the next refinement pass folds them in cleanly.
	const declaredRoutes = extractDeclaredRoutes(flowsContents);
	const undeclaredPeeks = peeks.filter((p) => !declaredRoutes.has(p.route));
	const orphanDeclaredRoutes = [...declaredRoutes].filter(
		(r) => !peeks.some((p) => p.route === r),
	);

	const projectSection = `## Project context\n\n${renderProjectMeta(meta)}\n`;
	const screensSection =
		peeks.length > 0
			? `## Screens (with code peeks)\n\n${peeks.map(renderScreenPeek).join("\n\n")}\n`
			: "";
	const undeclaredSection =
		undeclaredPeeks.length > 0
			? `## Routes in app/ not yet declared in snap-flows.ts\n\nThese routes exist on disk but the current declaration doesn't include them. Fold them into the right user-journey flow as part of your refinement — don't leave them in a "Recently added" bucket.\n\n${undeclaredPeeks.map((p) => `- \`${p.route}\` → ${p.docComment ? p.docComment.slice(0, 120) : `(see screen peek above)`}`).join("\n")}\n`
			: "";
	const orphanSection =
		orphanDeclaredRoutes.length > 0
			? `## Declared routes that no longer exist in app/\n\nThese routes are in snap-flows.ts but the file scan didn't find them — they may have been removed or renamed. Drop them from the declaration unless you have reason to keep them.\n\n${orphanDeclaredRoutes.map((r) => `- \`${r}\``).join("\n")}\n`
			: "";
	const flowsSection = `## Current snap-flows.ts\n\n\`\`\`ts\n${flowsContents}\n\`\`\``;

	const sections = [
		PROMPT_HEADER,
		projectSection,
		screensSection,
		undeclaredSection,
		orphanSection,
		flowsSection,
		PROMPT_FOOTER,
	].filter(Boolean);
	const clipboardPayload = sections.join("\n");

	const flowMatches = flowsContents.match(/\bid:\s*["'][^"']+["']/g) ?? [];
	const screenMatches =
		flowsContents.match(/\broute:\s*["'][^"']+["']/g) ?? [];
	const summaryParts: string[] = [
		`${flowMatches.length} flows`,
		`${screenMatches.length} screens`,
	];
	if (peeks.length > 0) summaryParts.push(`${peeks.length} peeks`);
	if (undeclaredPeeks.length > 0)
		summaryParts.push(`${undeclaredPeeks.length} undeclared`);
	if (orphanDeclaredRoutes.length > 0)
		summaryParts.push(`${orphanDeclaredRoutes.length} orphan`);
	const summary = summaryParts.join(", ");

	return {
		clipboardPayload,
		flowsFilePath,
		summary,
	};
}

/**
 * Pull all `route: "..."` literals out of an existing snap-flows.ts so we
 * can diff them against what's actually in app/. Same regex shape as the
 * CLI's --merge mode helper. Naive but reliable for declaration files.
 */
function extractDeclaredRoutes(src: string): Set<string> {
	const set = new Set<string>();
	const re = /route\s*:\s*["'`]([^"'`]+)["'`]/g;
	let m: RegExpExecArray | null;
	while ((m = re.exec(src))) {
		if (m[1]) set.add(m[1]);
	}
	return set;
}
