/**
 * "✨ Improve with Claude" — clipboard-mode helper.
 *
 * Reads a project's snap-flows.ts, builds a structured prompt that asks
 * Claude to regroup flows by user-journey (instead of the dumb path-
 * based default the CLI generates), and returns the combined string so
 * the view can copy it to the clipboard. The user pastes into Claude
 * Code, reviews the diff, and saves — Capture stays out of the API
 * billing surface.
 *
 * No remote calls, no API keys. Works for everyone.
 */

import { readFileSync } from "node:fs";
import { findProjectForBridge } from "./init";

export interface ImproveResult {
	/** Single string the view copies to the clipboard. */
	clipboardPayload: string;
	/** The path to snap-flows.ts so the toast can reference it. */
	flowsFilePath: string;
	/** Human summary for the toast (e.g. "47 screens, 14 flows"). */
	summary: string;
}

const PROMPT_HEADER = `# Improve snap-flows.ts

The file below is auto-generated by snap-bridge's CLI from this RN project's
\`app/\` route tree. The default grouping is path-based and doesn't reflect
how a real user moves through the product. Regroup it semantically.

## Rules

1. Keep every \`route\` value VERBATIM — no edits to paths.
2. Group by user journey, not by URL prefix. Examples:
   - \`/sign-in\`, \`/sign-up\`, \`/forgot-password\` → an "Auth" flow even if
     they live under different paths.
   - Anything that's part of a multi-step booking experience (browse,
     pick activity, payment, confirmation) → "Booking flow" with sub-flows
     for sub-steps.
   - Profile + settings + account management → "Profile / settings".
3. Use sub-flows (\`flows: [...]\`) for genuinely nested experiences. Don't
   over-nest — keep depth ≤ 2.
4. Display order should mirror a natural product walkthrough — onboarding
   first, primary feature loops next, settings/admin last.
5. Screen \`name\` should match feature-uppercase product wording, not
   route slugs ("Booking summary" not "Booking-summary").
6. Add \`stateHash\` filters where two routes share a path but differ in
   meaningful state (e.g. logged-out vs logged-in home).
7. Preserve the \`SnapFlowsDeclaration\` type contract. Output the FULL
   updated file, ready to paste over the existing one.

## Current snap-flows.ts

\`\`\`ts
`;

const PROMPT_FOOTER = `\`\`\`

Output: the entire updated snap-flows.ts contents, wrapped in a single
\`\`\`ts code fence. After the file, give me a 2-3 line summary of what you
changed (added flows, renamed screens, sub-flow restructuring).
`;

export function buildImprovePrompt(slug: string): ImproveResult {
	const project = findProjectForBridge(slug);
	if (!project) {
		throw new Error(`No project with slug "${slug}"`);
	}
	const rnAppDir = project.rnAppDir;
	if (!rnAppDir) {
		throw new Error(`Project "${slug}" has no rnAppDir on disk`);
	}

	const flowsFilePath = `${rnAppDir}/snap-flows.ts`;
	let contents: string;
	try {
		contents = readFileSync(flowsFilePath, "utf8");
	} catch (err) {
		throw new Error(
			`Couldn't read ${flowsFilePath}: ${(err as Error).message}. Run snap-flows-scan first.`,
		);
	}

	const flowMatches = contents.match(/\bid:\s*["'][^"']+["']/g) ?? [];
	const screenMatches = contents.match(/\broute:\s*["'][^"']+["']/g) ?? [];
	const summary = `${flowMatches.length} flows, ${screenMatches.length} screens`;

	return {
		clipboardPayload: PROMPT_HEADER + contents + PROMPT_FOOTER,
		flowsFilePath,
		summary,
	};
}
